### PR TITLE
Show legend text on modal

### LINKED ISSUE #368: Legend text does not appear on modal legend
I'm not sure if this is as intended or not.

legend1

### PR DESCRIPTION
**Pull request by jfrankl**
Fixes #368. Previously, this text was hidden on mobile screen sizes.

### CODE REVIEW

**Comment by jfrankl** [comment]
image

**Comment by RickMohr** [comment]
In mobile I don't see the reservations text, just the legend:

image

**Comment by maurizi** [comment]
@RickMohr There are no changes to the "Reservations" page (since I'm in the process of deleting it), just the "New Reservations Page"

**Comment by RickMohr** [comment]
In desktop view the progress text is cut off:

image

**Comment by jfrankl** [comment]
@RickMohr: fixed your issue here: c1b3aa9caf669b11ac8dff8ab37c9a36e9648cd3

Your question about block sides vs block faces: I am going to pull that into a different issue.

We should be good to go here.

**Comment by RickMohr** [comment]
+1 looks good!

**Comment by maurizi** [comment]
+1

**Pull request merged**
