### PR TITLE
Update page copy

### LINKED ISSUE #848: Add text provided by Parks

### PR DESCRIPTION
**Pull request by jwalgran**
The text was provided by Parks.

The one adjustment I made to the sass was to compensate for the word
"Attending" being a longer than "RSVPed"

Fixes #848

screen shot 2015-03-18 at 3 42 01 pm

screen shot 2015-03-18 at 3 40 25 pm

screen shot 2015-03-18 at 3 39 57 pm

screen shot 2015-03-18 at 3 39 28 pm

screen shot 2015-03-18 at 3 39 06 pm

screen shot 2015-03-18 at 3 37 53 pm

screen shot 2015-03-18 at 3 37 38 pm

screen shot 2015-03-18 at 3 36 42 pm

screen shot 2015-03-18 at 3 35 24 pm

screen shot 2015-03-18 at 3 34 29 pm

screen shot 2015-03-18 at 3 34 05 pm

screen shot 2015-03-18 at 3 34 03 pm

screen shot 2015-03-18 at 3 33 58 pm

screen shot 2015-03-18 at 3 26 31 pm

screen shot 2015-03-18 at 3 26 17 pm

screen shot 2015-03-18 at 3 25 02 pm

screen shot 2015-03-18 at 3 24 51 pm

### CODE REVIEW

**Comment by dboyer** [comment]
The groups page is missing a period after the last sentence (events occurring near you). 

I also don't like how only one sentence wraps below the Parks logo on the homepage. Is there anyway to change that?

**Comment by jwalgran** [comment]
@designmatty do you have a preference for how we keep the text from flowing under the logo>

https://cloud.githubusercontent.com/assets/17363/6721139/0d0672ee-cd87-11e4-816c-51783ddd72ba.png

**Comment by jwalgran** [comment]
I added the missing period

**Comment by designmatty** [comment]
I would recommend using the bootstrap grid to fix this. Place the `` within a column and the `<p>` within another column.

**Pull request merged**
