### PR TITLE
Show all RSVPd events on "Your Events this week"

### LINKED ISSUE #1027: "Your events this week" list not showing RSVPd events in the near future
screen shot 2015-04-01 at 10 21 27 am

screen shot 2015-04-01 at 10 21 51 am

### PR DESCRIPTION
**Pull request by kdeloach**
Only display events that you have explicitly RSVPd to on the events
listing page.

Test this by RSVPing to an upcoming event that belongs to a group that you are *not* following. The event should appear in "Your events this week".

Fixes #1027

### CODE REVIEW

**Comment by kdeloach** [comment]
Fixing tests now.

**Comment by kdeloach** [comment]
Updated.

**Comment by steventlamb** [comment]
+1 for review, will test tomorrow

**Comment by steventlamb** [comment]
+1

**Pull request merged**
