### PR TITLE
Change language for training/mapping events

### LINKED ISSUE #1442: Change reservations instructions
The third step should be "attend a mapping event" rather than "attend a second training event."

If this series of steps is listed anywhere else, we should make the same change.

### PR DESCRIPTION
**Pull request by RickMohr**
* "Mapping event" instead of "second training event"
* "Training event" instead of "first training event"

Fixes #1442

### CODE REVIEW

**Comment by RickMohr** [comment]
waffle

**Comment by RickMohr** [comment]
waffle 2

**Comment by RickMohr** [comment]
waffle three

**Comment by maurizi** [comment]
+1

**Pull request merged**
