### PR TITLE
Feature/style

### PR DESCRIPTION
**Pull request by jfrankl**

### CODE REVIEW

**Comment by jfrankl** [comment]
image

**Comment by kdeloach** [comment]
+1

**Comment by jwalgran** [comment]
@jfrankl We have this open issue to add the event time to the event detail page. https://github.com/azavea/nyc-trees/issues/493 
Where would you prefer we add the time field?

**Comment by jfrankl** [comment]
Please add it above the location in the list to the right of the
calendar/date.

On Fri, Feb 13, 2015 at 10:52 AM, Justin Walgran <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> We have this open issue to add the
> event time to the event detail page. #493
> <https://github.com/azavea/nyc-trees/issues/493>
> Where would you prefer we add the time field?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/520#issuecomment-74274888>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Pull request merged**
