### PR TITLE
Make email address visible on group detail page

### PR DESCRIPTION
**Pull request by kdeloach**
Connects #236

### CODE REVIEW

**Comment by kdeloach** [comment]
Preview:
image

**Comment by kdeloach** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
All (or almost all) of the clickable things in the app are either blue or green, so sticking with that convention for this clickable link, and coloring it blue, is a good idea.

**Comment by kdeloach** [comment]
Made the link blue and also inlined it (instead of floating right) to prevent long email address from bleeding over the edge.

**Comment by kdeloach** [comment]
@jfrankl Which do you prefer? With or without the icon?

image

image

**Comment by kdeloach** [comment]
Here is the final result after restoring the Email button and slightly altering the layout. The contact email below the contact name is unstyled but still clickable. Also updated the event detail page to match.

image

image

**Comment by jfrankl** [comment]
+1

On Wed, May 13, 2015 at 3:55 PM, Kevin DeLoach <notifications@github.com>
wrote:

> Assigned #1621 <https://github.com/azavea/nyc-trees/pull/1621> to @jfrankl
> <https://github.com/jfrankl>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/1621#event-304244546>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Pull request merged**
