### PR TITLE
Add minimum input and placeholder text to species autocomplete

### PR DESCRIPTION
**Pull request by maurizi**
Connects to #1538

### CODE REVIEW

**Comment by dboyer** [comment]
I'm not sure about the "Select and type species name." Is there a reason to not have just "Start typing species name"? Or "Start typing species and then select from list" ?

**Comment by RickMohr** [comment]
The goal was getting them to tap in the text area rather than hitting the drop-down. I proposed "Tap and type species name". @maurizi preferred "Select and type species name".

**Comment by maurizi** [comment]
@dboyer If you look at the attached screenshots, the placeholder text shows up *before* you have tapped/clicked on the species dropdown, and so in is incorrect to tell people to type to choose a species, since they must open the dropdown first.

There is no option in the library we are using to _easily_ show placeholder text once the dropdown is open (though it does have the "please enter X or more characters" text).

**Comment by maurizi** [comment]
And using "Start typing species and then select from list" both neglects to tell people to open the dropdown first *and* it is too long to fit on small screens

**Comment by dboyer** [comment]
Okay let's stick with "Select and type species name"

**Comment by steventlamb** [comment]
+1 tested

**Pull request merged**
