### PR TITLE
style changes for select2 to match bootstrap styling

### PR DESCRIPTION
**Pull request by designmatty**
This will update the look of select2 dropdowns to match the theme.

### CODE REVIEW

**Comment by jwalgran** [comment]
Looks good to me

screen shot 2015-03-09 at 7 56 15 am

screen shot 2015-03-09 at 7 56 28 am

**Comment by jfrankl** [comment]
+1

On Mon, Mar 9, 2015 at 10:57 AM, Justin Walgran <notifications@github.com>
wrote:

> Looks good to me
>
> [image: screen shot 2015-03-09 at 7 56 15 am]
> <https://cloud.githubusercontent.com/assets/17363/6557388/dc7ca4c4-c631-11e4-9445-14cfdbb97f37.png>
>
> [image: screen shot 2015-03-09 at 7 56 28 am]
> <https://cloud.githubusercontent.com/assets/17363/6557392/e0703d16-c631-11e4-998f-d2e01654b1d2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/783#issuecomment-77868733>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by RickMohr** [comment]
As seen in Justin's picture, the tree common name and scientific name In the drop-down currently have vanilla developer styling and could benefit from design help. Is It possible to compress vertically so two entire choices can be seen on a mobile device with its keyboard present?

Happy to open a separate issue if that's more appropriate.

**Comment by designmatty** [comment]
@RickMohr would you like to open a new issue for this? I'm going to merge this in at its current state to be ready for noon.

**Pull request merged**
