### PR TITLE
Get deployment working again

### LINKED ISSUE #1847: Deprecation warnings when using Ansible 2.0
```
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and
make sure become_method is 'sudo' (default). This feature will be removed in a
future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```

```
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{app_sauce_labs_config}}'). This feature will be removed in a future
release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```

### PR DESCRIPTION
**Pull request by hectcastro**
Adds Ansible 2.0 support and ensures that the development, testing, and deployment processes are up-to-date.

Resolves #1847

### CODE REVIEW

**Comment by maurizi** [comment]
I'm testing this out locally, with `VAGRANT_ENV=development`.

Seems to be working well, with a couple of deprecation warnings, which would be nice but not critical to fix.

Installing roles:
```
- azavea.postgresql-support was installed successfully
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
```
Bringing up the services VM:
```
==> services: Configuring cache buckets...
==> services: Running provisioner: ansible...
    services: Running ansible-playbook...
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default). This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

Installing Beaver (happens on both the `app` and `tiler` VMs):
```
TASK [azavea.beaver : Install Beaver dependencies] *****************************
Monday 18 April 2016  11:51:55 -0400 (0:00:00.308)       0:00:30.906 ********** 
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your 
playbooks so that the environment value uses the full variable syntax 
('{{beaver_dependencies}}'). This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
skipping: [tiler] => (item={u'version': u'0.12', u'name': u'docutils'}) 
skipping: [tiler] => (item={u'version': u'2.0.2', u'name': u'python-daemon'})
```

**Comment by maurizi** [comment]
Also looks good with `VAGRANT_ENV=TEST`

**Comment by maurizi** [comment]
Since the packer job is working properly, the tests pass, and this can provision for development, I think this is good to go.

:+1:

**Comment by hectcastro** [comment]
The first I've never really definitely tracked down (it is unclear what actually trips it). The second I'm having a bit of trouble reproducing locally, and the third is in https://github.com/azavea/ansible-beaver/pull/10.

**Pull request merged**
