### PR TITLE
Add code for submitting treecorder surveys

### PR DESCRIPTION
**Pull request by maurizi**
Also fixes a few bugs with the treecorder markup

### CODE REVIEW

**Comment by kdeloach** [comment]
Minor issue, but it looks like something is trying to focus hidden form fields when there is a validation error.
image

**Comment by maurizi** [comment]
@kdeloach Huh, weird.  Good catch, I'll look into it

**Comment by kdeloach** [comment]
Is there a management command or SQL to insert species data into the database?

**Comment by maurizi** [comment]
@kdeloach I just used the Django Admin site

**Comment by kdeloach** [comment]
Got it, thanks.

**Comment by kdeloach** [comment]
Do species appear in the Django admin for you? I had to use pgweb.

**Comment by maurizi** [comment]
@kdeloach Odd, it definitely used to be there....

**Comment by kdeloach** [comment]
Pressing the enter button triggers validation but it doesn't seem to submit the form when there are no validation errors. Not sure if this is by design or not.

**Comment by kdeloach** [comment]
+1 I'm able to survey blockfaces now.

**Comment by maurizi** [comment]
I didn't consider the enter button at all, so that's definitely not by design.
I'm inclined to leave that as is for now.

**Comment by maurizi** [comment]
@kdeloach I fixed the "unfocusable" bug.

**Pull request merged**
