### PR TITLE
Show submitted questions/answers summary after completing a quiz

### PR DESCRIPTION
**Pull request by kdeloach**
How to test:
1. Complete the training quiz
2. The quiz results page should display the answers you selected and whether or not they are correct.

### CODE REVIEW

**Comment by kdeloach** [comment]
My goal is to have this merged in by tomorrow morning.

**Comment by RickMohr** [comment]
Need a period after "Your best score so far was 2/3"

**Comment by RickMohr** [comment]
Suggested format tweaks:
* Remove exclamation points
* Remove line break before "You answered"
* Change "..." to ":" after "You answered"
* "Not correct" instead of "Wrong"

Example:

2. Lorem ipsum dolor sit amet, consectetur adipiscing elit?

Not correct. You answered:

Answer B

**Comment by RickMohr** [comment]
Otherwise +1, good improvement.

**Comment by kdeloach** [comment]
Done and done.

**Pull request merged**
