### PR TITLE
Topic/959/update training content

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by maurizi** [comment]
The photo assets added here are going to be brought into our Gulp pipeline, subjecting them to versioning via `gulp-rev-all`.

Because of the, referring to them via `` won't work in production.

We may be able to sidestep the issue by ignoring the entire folder, like we do for our font assets: https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/gulpfile.js#L96-L97

The only downside to this is that nginx will still mark them to be cached forever.
We can probably work around that if need be by just changing the filenames whenever we need to change a training image.

**Comment by jwalgran** [comment]
Using a subfolder and adding an additional ``location`` to nginx, in combination with disabling versioning, may get us where we need to be. I am not sure if the location matching will work as I am assuming it will.
```
  location /static/content/ {
    {% if ['packer'] | is_in(group_names) -%}
    expires 2h;
    {% endif %}
 
    alias {{ app_static_root }}content/;
  }

  location /static/ {
    {% if ['packer'] | is_in(group_names) -%}
    etag on;
    expires max;
    {% endif %}

    alias {{ app_static_root }};
  }

**Comment by steventlamb** [comment]
@maurizi @jwalgran updated to solve image problem.

**Comment by jwalgran** [comment]
+1 I deleted all my flatpages, ran the management command, and then walked through the training process, viewing the new content and answering the real quiz questions. The images copied to ``/var/www/static/img/training`` did not get versioned file names.

**Comment by steventlamb** [comment]
fixes #959

**Pull request merged**
