### PR TITLE
Add icons on all event partials

### LINKED ISSUE #1095: Add event icons on all events
Right now the events page shows certain icons for location/type/etc but these are not displayed on other pages.

image

image

### PR DESCRIPTION
**Pull request by jfrankl**
Fixes #1095.

image

### CODE REVIEW

**Comment by RickMohr** [comment]
Consider a bit of white space between icon and text?

**Comment by jfrankl** [comment]
@RickMohr 

Extra padding:

image

**Comment by RickMohr** [comment]
Nice!! Thanks.

**Comment by jfrankl** [comment]
@steventlamb, c847d62 adds icons on group admin page.

**Comment by steventlamb** [comment]
+1

**Pull request merged**
