### PR TITLE
Send Email when blockfaces are reserved

### LINKED ISSUE #434: Send email after confirming blockface reservations and after PDF is generated

### PR DESCRIPTION
**Pull request by steventlamb**
fixes #434 on github

### CODE REVIEW

**Comment by steventlamb** [comment]
This is essentially a preview, as it depends on other features

**Comment by RickMohr** [comment]
+1 pending integration

**Comment by steventlamb** [comment]
I've got this working in dev:
```
[2015-03-26 11:52:12,221: INFO/MainProcess] Received task: libs.pdf_maps.create_and_save_pdf[2f8d2603-1b6f-410a-9641-08523e5bac96]
[2015-03-26 11:52:12,230: DEBUG/MainProcess] Task accepted: libs.pdf_maps.create_and_save_pdf[2f8d2603-1b6f-410a-9641-08523e5bac96] pid:9334
[2015-03-26 11:52:24,398: WARNING/Worker-1] MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: Your blockface reservations are confirmed!
From: MASKED
To: MASKED
Date: Thu, 26 Mar 2015 15:52:24 -0000
Message-ID: <20150326155224.9334.19381@app>

Your blockface reservations are confirmed!

The following blockfaces have been confirmed:

* 30514


You can view a summary of your reservations at /media/reservations_map/vagrant_9pKPYH9ZtzNkxcpBFt73YQ.pdf
[2015-03-26 11:52:24,406: WARNING/Worker-1] -------------------------------------------------------------------------------
```

The url isn't ready for primetime, at least on dev.

**Comment by RickMohr** [comment]
You can get the full URL using `user.reservations_map_pdf_url`

**Comment by jwalgran** [comment]
I would like to pair up and unify this with #937

**Comment by RickMohr** [comment]
They are a bit different. 

With reservations we get control when the user is checking out new reservations. We know we need to generate a new PDF, so I thought the plan was to sequence two celery tasks, the first to generate the PDF and the second to send the e-mail. That would take some refactoring.

With events we get control when the user RSVP's. There's a tiny chance that the PDF is being generated when we want to send the e-mail. Probably a short retry/sleep loop would handle it.

**Comment by steventlamb** [comment]
@jwalgran good to merge?

**Comment by steventlamb** [comment]
took this for another spin and I've got binary pdf data in my console :tangerine:

**Comment by jwalgran** [comment]
``create_and_save_pdf`` still has the code that complects notifications with PDF generation. We should probably back that out now that we have a proper task chain.

**Comment by steventlamb** [comment]
@jwalgran cool. I squashed that backout into your first commit, seemed like the logical place.

**Comment by steventlamb** [comment]
tested again, still works

**Comment by jwalgran** [comment]
+1

**Pull request merged**
