### PR TITLE
Dump events table as shapefile instead of CSV.

### LINKED ISSUE #935: Export events as shapefile instead of as a text file

### PR DESCRIPTION
**Pull request by maurizi**
Fixes #935

### CODE REVIEW

**Comment by maurizi** [comment]
@RickMohr If you have the time to, I'd apreciate if you could test it out.

Feel free to reassign this to me if you don't think you'll be able to test this.

**Comment by RickMohr** [comment]
Open a Django shell and call the function?

**Comment by maurizi** [comment]
Run the management command: `./scripts/manage,sh dump_db`.  This should create a `dump.zip` inside your VM in `/var/www/nyc-trees/media/dump/`

**Comment by maurizi** [comment]
You may have to delete rows from the `core_taskrun` table if the `dump_db` command was already run today.

**Comment by RickMohr** [comment]
I only see `trees.shp, not `events.shp` or `blockface.shp`:
```
vagrant@app:/var/www/nyc-trees/media/dump/2015-04-14$ ls -l
total 216
-rw-r--r-- 1 celery celery    228 Apr 14 20:23 achievement.csv
-rw-r--r-- 1 celery celery   2409 Apr 14 20:23 blockfacereservation.csv
-rw-r--r-- 1 celery celery    279 Apr 14 20:23 eventregistration.csv
-rw-r--r-- 1 celery celery     56 Apr 14 20:23 follow.csv
-rw-r--r-- 1 celery celery    782 Apr 14 20:23 group.csv
-rw-r--r-- 1 celery celery  17115 Apr 14 20:23 species.csv
-rw-r--r-- 1 celery celery    172 Apr 14 20:23 survey.csv
-rw-r--r-- 1 celery celery 142203 Apr 14 20:23 territory.csv
-rw-r--r-- 1 celery celery    163 Apr 14 20:23 trainingresult.csv
-rw-r--r-- 1 celery celery     10 Apr 14 20:23 trees.cpg
-rw-r--r-- 1 celery celery    577 Apr 14 20:23 trees.dbf
-rw-r--r-- 1 celery celery    143 Apr 14 20:23 trees.prj
-rw-r--r-- 1 celery celery    100 Apr 14 20:23 trees.shp
-rw-r--r-- 1 celery celery    100 Apr 14 20:23 trees.shx
-rw-r--r-- 1 celery celery     70 Apr 14 20:23 trustedmapper.csv
-rw-r--r-- 1 celery celery   1908 Apr 14 20:23 user.csv
```

**Comment by maurizi** [comment]
Did you restart your Celery service after pulling down the branch?

**Comment by RickMohr** [comment]
Works (ignore coarse base map).

image  image

**Pull request merged**
