### PR TITLE
Apply full screen map style to additional maps

### PR DESCRIPTION
**Pull request by jfrankl**

### CODE REVIEW

**Comment by jfrankl** [comment]
This fixes some full screen mapping styles and applies them to multiple maps:

- Progress
- Reservations
- New Reservations

**Comment by jfrankl** [comment]
image

image

image

**Comment by kdeloach** [comment]
Very slick.

Unrelated to this PR, but do you know if we have locked down minimum screen resolution requirements? Here's what this looks like on my device.

screenshot_2015-01-27-10-30-10
screenshot_2015-01-27-10-30-25

**Comment by kdeloach** [comment]
+1

**Pull request merged**
