### PR TITLE
Show map with group territory on group detail page

### PR DESCRIPTION
**Pull request by RickMohr**

### CODE REVIEW

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
This looks good and the group map is showing territory on my machine.

The /blockface/reserve/ page is working in staging, but not on this branch on my machine. On this branch, clicking a blockface increments the count of reserved blockfaces, but does not highlight the feature. Is this something strange on my machine, or did mapping refactor introduce a regression?

**Comment by RickMohr** [comment]
@jwalgran, the /blockface/reserve/ page works fine for me on this branch, and I don't appear to have any uncommitted changes.

**Comment by jwalgran** [comment]
That's good. Must be some goofyness with my build. I will try again.

**Comment by RickMohr** [comment]
I take it back, I was on the wrong branch. Looks like a regression, investigating.

**Comment by RickMohr** [comment]
@jwalgran, fixed. Since I saw it fail, fixed it, and saw it work, you probably don't need to pull it down again but  let me know if you want to.

**Comment by jwalgran** [comment]
I have my VM up. I'll give it a once-over

**Comment by jwalgran** [comment]
+1

**Pull request merged**
