### PR TITLE
Add About & FAQ page

### PR DESCRIPTION
**Pull request by maurizi**
about_faq

### CODE REVIEW

**Comment by maurizi** [comment]
@dboyer @jfrankl Let me know if the attached screenshot looks Ok.

**Comment by dboyer** [comment]
Looks fine to me.

**Comment by hectcastro** [comment]
@azavea-bot rebuild

**Comment by jfrankl** [comment]
+1

On Tue, Mar 31, 2015 at 9:03 AM, Hector Castro <notifications@github.com>
wrote:

> @azavea-bot <https://github.com/azavea-bot> rebuild
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/992#issuecomment-88075593>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
Looking at this now

**Comment by jwalgran** [comment]
Needs to be added to the soft launch whitelist

**Comment by maurizi** [comment]
@jwalgran Done

**Comment by jwalgran** [comment]
+1

**Pull request merged**
