### PR TITLE
Topic/dont version training pdf

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by maurizi** [comment]
I feel very wary about including commit caa142a right now.
It's a semantically small change, but affects every page on the site, and I'm worried a file will have been missed somewhere.

**Comment by steventlamb** [comment]
I don't have a problem dropping caa142a, and I will fix the urljoin thing.

**Comment by jwalgran** [comment]
Looks like this may still be in the oven. Toss it back when it is ready.

**Comment by steventlamb** [comment]
@jwalgran closing this and assigning to the lighter version to you.

**Pull request closed without merging**
