### PR TITLE
Use same logic for selecting blockface from hash as used for crosshairs

### PR DESCRIPTION
**Pull request by maurizi**
Connects to #1542

### CODE REVIEW

**Comment by maurizi** [comment]
Waffle

**Comment by RickMohr** [comment]
#1542 appears to be fixed, but not #1514. 

On page load (if there is no deep-linked blockface) we want to see if there is a blockface underneath the crosshairs, and select it if so.

**Comment by maurizi** [comment]
@RickMohr You're right, my bad!  I'll just disconnect that issue from this PR.

**Comment by RickMohr** [comment]
+1

**Pull request merged**
