### PR TITLE
Add geocoder to add event page

### LINKED ISSUE #949: Add geocoder to event creation
Group admins could set event location based on address. They could move the dot to adjust location, but it would not change the address.

### PR DESCRIPTION
**Pull request by kdeloach**
If you press "enter" with the address field focused, or click the
search button, the small map will move to the geocoded address.

Fixes #949

### CODE REVIEW

**Comment by kdeloach** [comment]
Needs styling!
image

**Comment by dboyer** [comment]
Added a new issue for styling - #995

**Comment by kdeloach** [comment]
Fixed lint.

**Comment by jwalgran** [comment]
Looking at this now

**Comment by jwalgran** [comment]
+1 works

**Pull request merged**
