### PR TITLE
Topic/1110/add training images

### PR DESCRIPTION
**Pull request by steventlamb**
@dboyer notice that 'Evidence of Stewardship' does not exist in the training materials but is references in the quiz. I think they meant `Stewardship Practices', so I went with that, but left the text as is.

### CODE REVIEW

**Comment by dboyer** [comment]
That sounds great.

**Comment by steventlamb** [comment]
bumping to @jwalgran for regular code review now that PM question is resolved.

**Comment by jwalgran** [comment]
Reviewing

**Comment by jwalgran** [comment]
The http://localhost:8000/training/pure/the_mapping_method/#what-if-there-arent-any-trees anchor is missing

**Comment by jwalgran** [comment]
I see 3 images during the quiz.

screen shot 2015-04-16 at 10 02 46 am

screen shot 2015-04-16 at 10 02 01 am

screen shot 2015-04-16 at 10 01 45 am

**Comment by jwalgran** [comment]
+1 after anchor fix

**Comment by steventlamb** [comment]
hmmm. http://localhost:8000/training/pure/the_mapping_method/#what-if-there-arent-any-trees works for me on this branch, after running `scripty clobber_training_flatpages` and making sure my user is progressed far enough to have access. Can you double check this?

**Comment by jwalgran** [comment]
Ah yes, I didn't clobber the flatpages. +1

**Pull request merged**
