### PR TITLE
fixed cropped logo and introduced retina logo

### LINKED ISSUE #1030: Parks logos cut off
This is on production.

In the header, the circle appears cut off slightly along the bottom and right side.

In the center of the page, the NYC Parks text is cut off along the bottom. 

parks-logo-small

### LINKED ISSUE #1031: Replace parks and treescount logos with higher quality and retina versions

### PR DESCRIPTION
**Pull request by designmatty**
fixes #1031 and fixes #1030

### CODE REVIEW

**Comment by jfrankl** [comment]
Looks great on desktop.

Seems like it displays wider than the previous image. Right now it covers up the Login/Register buttons on iPhone 5:

image

**Comment by designmatty** [comment]
Hmm I'll look into that.

**Comment by designmatty** [comment]
@jfrankl okay should be fixed up

**Comment by jfrankl** [comment]
+1 cream of the crop

**Comment by designmatty** [comment]
ahh I see what you did there.

**Pull request merged**
