### PR TITLE
Move dashboard and home to switchable partials

### PR DESCRIPTION
**Pull request by jwalgran**
Build on top of @jfrankl 's homepage styling PR.

The content of the root page changes depending on whether the user is logged in or not. To accomplish this, home.html now conditionally loads either home_public.html or dashboard.html partials.

### CODE REVIEW

**Comment by jwalgran** [comment]
@jfrankl switching partials on the ``home.html`` page seems like the cleanest way to handle showing different pages based on whether or not a user is logged in.

**Comment by kdeloach** [comment]
+1

**Comment by jfrankl** [comment]
Looks good to me too.

On Tue, Feb 3, 2015 at 10:15 AM, Kevin DeLoach <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/430#issuecomment-72667504>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
+1 looks great

**Pull request merged**
