### PR TITLE
Remove some neighborhood polygons.

### PR DESCRIPTION
**Pull request by maurizi**
Removes the polygons from the fixture and adds a data migration to delete
them if they already exist.

Connects to #1636

### CODE REVIEW

**Comment by jwalgran** [comment]
Blackfaces that have been assigned to these NTAs must have their FK set to null before trying to delete the NTAs.

```
  Applying survey.0026_auto_20150514_1005...Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/opt/app/apps/survey/migrations/0026_auto_20150514_1005.py", line 16, in delete_ntas
    'MN99', 'BK99', 'BX99', 'QN99', 'SI99', 'QN98', 'BX98']).delete()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 556, in delete
    collector.collect(del_query)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 199, in collect
    field.rel.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 17, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 199, in collect
    field.rel.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: (u"Cannot delete some instances of model 'Blockface' because they are referenced through a protected foreign key: 'Survey.blockface'", [<Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, <Survey: Survey object>, '...(remaining elements truncated)...'])

**Comment by maurizi** [comment]
@jwalgran I've fixed that by setting the `on_delete` properties in `Blockface` to `SET_NULL`.

**Comment by jwalgran** [comment]
I get the same exception. Changing field properties requires making a migration and that migration should come before the data migration. You could also side step this whole issue by just nulling out the FKs in the data migration and letting the management command that is part of ``setupdb.sh`` handle reassigning the regions to the blocks.

**Comment by maurizi** [comment]
@jwalgran I followed your advice on just nulling out the nta foreign key from every blockface

**Comment by jwalgran** [comment]
+1

Dark blue is the original shapefile, green is the migrated NTA layer. 

screen shot 2015-05-14 at 9 04 05 am

App shows no polygons over parks, etc.

screen shot 2015-05-14 at 9 16 21 am

**Pull request merged**
