### PR TITLE
Show block edge endpoints on printable reservations map

### LINKED ISSUE #904: Add corner points for blockfaces on the printable context map for individual mappers
The corner points on the printable map can be the same symbology as the corner points that show in the Treecorder when choosing a starting point. Some blocks are curved and the corner point is meant to help the mapper know where to start mapping.

### PR DESCRIPTION
**Pull request by RickMohr**
* Python code creates list of endpoints
* Template stores it in a map data attribute
* JavaScript puts endpoint circle markers in a Leaflet layer

Fixes #904

### CODE REVIEW

**Comment by RickMohr** [comment]
waffle

**Comment by RickMohr** [comment]
waffle take 2

**Comment by jwalgran** [comment]
Looks good. Testing now.

**Comment by jwalgran** [comment]
+1 Endpoint markers are showing up in the reservation PDF

screen shot 2015-04-13 at 8 40 39 am

**Comment by RickMohr** [comment]
@jwalgran, from your picture I realized the circle radius should be zoom-sensitive. Updated. I will merge unless you want to take another look.

**Comment by jwalgran** [comment]
In the middle of some stuff. Doubling logic looks sound.

**Pull request merged**
