### PR TITLE
Add achievements page, link to it from user profile and nav bar

### LINKED ISSUE #606: Achievements in sidebar does not link to anything

### PR DESCRIPTION
**Pull request by maurizi**
Fixes #606

### CODE REVIEW

**Comment by maurizi** [comment]
The achievements page:
achievements

@dboyer @jfrankl I've also changed things slightly on the user profile.  When you are looking at your own user profile we now show a link to the achievements page.

If you are looking at someone else's user profile and they have not yet earned any achievements, the section is now hidden, since there is nothing is to show (since the achievements page shows *your* achievements)

**Comment by jfrankl** [comment]
This looks good to me.

**Comment by dboyer** [comment]
Fine by me too.

**Comment by steventlamb** [comment]
+1 I tested this both by completing training through the UI and by backdooring field training through the admin interface. Both achievements were moved to 'earned'.

**Pull request merged**
