### PR TITLE
Show error validation messages on iOS and old Android browsers

### PR DESCRIPTION
**Pull request by maurizi**
Switches from using builtin browser validation messages to custom messages.

We need to show custom error messages on iOS and older Android browsers, as they will not do so for us.  Since we are doing so for some browsers, I have opted to switch to custom error messages on all browsers.

We still rely on html5 for the actual validation checking, which does work on all mobile browsers.

Connects to #1664

### CODE REVIEW

**Comment by maurizi** [comment]
custom-errors

**Comment by RickMohr** [comment]
Otherwise, works great!

**Comment by maurizi** [comment]
@RickMohr I have added some animations when we hide elements after the data becomes valid.

I've tested it on firefox and Chrome in desktop and mobile emulation modes, can you retest on your iPhone?

**Comment by RickMohr** [comment]
+1, big improvement!

**Pull request merged**
