### PR TITLE
Hide tree size details until structure is chosen

### PR DESCRIPTION
**Pull request by steventlamb**
connects to #943 on github

### CODE REVIEW

**Comment by jwalgran** [comment]
Reviewing now

**Comment by jwalgran** [comment]
+1 This does hide the measurement description label until a structure is selected.

screen shot 2015-05-04 at 12 54 29 pm

screen shot 2015-05-04 at 12 54 47 pm

**Comment by jwalgran** [comment]
I want to get some feedback from @dboyer to make sure this adequately covers the workflow issue described in #943

**Comment by steventlamb** [comment]
@dboyer does this look like the correct workflow?
initial:
screenshot from 2015-05-05 10 57 38
first click:
screenshot from 2015-05-05 10 57 48
second click:
screenshot from 2015-05-05 10 57 59
third click:
screenshot from 2015-05-05 10 58 08
fourth click:
screenshot from 2015-05-05 10 59 18

**Comment by dboyer** [comment]
Yes, that workflow looks correct to me.

**Pull request merged**
