### PR TITLE
Feature/design

### PR DESCRIPTION
**Pull request by jfrankl**

### CODE REVIEW

**Comment by maurizi** [comment]
I'm seeing a couple of issues (for reference, these are all in Chrome):

My Reservations page in desktop mode:
desktop reservations

Homepage (Dashboard looks fine):
sticks up

**Comment by jfrankl** [comment]
I'll look into the reservations page. Could you be more specific about the issue on the homepage?

**Comment by maurizi** [comment]
The white area "sticks up".  It doesn't do that for the dashboard.

**Comment by maurizi** [comment]
Another issue - when you hover over the "x" on the privacy popup, the link becomes the same color as the background.

**Comment by maurizi** [comment]
+1

**Pull request merged**
