### PR TITLE
Add default template

### PR DESCRIPTION
**Pull request by jfrankl**
Add a default template that developers can use when they're working on a new page.

### CODE REVIEW

**Comment by jwalgran** [comment]
A helpful foundation. Our first draft pages don't have to be ugly anymore.

I will look into the strange build failure.

**Comment by jfrankl** [comment]
Thanks! Please keep me posted on the build failure—I'll hold off on merging this until that's sorted out.

**Comment by hectcastro** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
I checked out the branch and replicated the failure

```
$ ./scripts/npm.sh run build

...

[17:58:20] Starting 'collect-prod'...
[17:58:20] 'collect-prod' errored after 2.4 ms
[17:58:20] Error: spawn ENOMEM
    at errnoException (child_process.js:1001:11)
    at ChildProcess.spawn (child_process.js:948:11)
    at exports.spawn (child_process.js:736:9)
    at Object.exports.execFile (child_process.js:618:15)
    at exports.exec (child_process.js:589:18)
    at async.eachSeries.self.emit.gutil.PluginError.stdout (/opt/app/node_modules/gulp-
shell/index.js:37:19)                                                                 
    at iterate (/opt/app/node_modules/gulp-shell/node_modules/async/lib/async.js:149:13
)                                                                                     
    at Object.async.eachSeries (/opt/app/node_modules/gulp-shell/node_modules/async/lib
/async.js:165:9)                                                                      
    at DestroyableTransform._transform (/opt/app/node_modules/gulp-shell/index.js:33:11
)                                                                                     
    at DestroyableTransform.Transform._read (/opt/app/node_modules/through2/node_module
s/readable-stream/lib/_stream_transform.js:184:10)

**Comment by jwalgran** [comment]
I checked out ``develop`` and ``build`` ran successfully.

**Comment by jfrankl** [comment]
What's the next step, @jwalgran?

**Comment by jwalgran** [comment]
Hang tight. We'll get it sorted.

**Comment by jwalgran** [comment]
Second CI build failed in a completely different spot. Definitely not related to this PR.

```
TASK: [nyc-trees.app | Install application Python dependencies for development and test] *** 
ok: [app] => (item=development)
failed: [app] => (item=test) => {"failed": true, "item": "test", "parsed": false}
SUDO-SUCCESS-pdvihovnqclophtzoqevpxukqurbwnzp

**Comment by jwalgran** [comment]
@azavea-bot rebuild

**Comment by hectcastro** [comment]
I don't think this rebuild triggered because I had the job disabled.

**Comment by hectcastro** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
@jfrankl The gremlins have departed. GTG.

**Pull request merged**
