### PR TITLE
Add footer with link to help email address to every email.

### LINKED ISSUE #922: Add a base email template and include treescount.help@parks.nyc.gov in the footer

### PR DESCRIPTION
**Pull request by maurizi**
Fixes #922

### CODE REVIEW

**Comment by jwalgran** [comment]
Looking at this now

**Comment by jwalgran** [comment]
The username recovery email is missing the new footer 

screen shot 2015-03-31 at 8 18 41 am

**Comment by jwalgran** [comment]
These other emails look good:

Account activation
Blockface reservation confirmation
RSVP confirmation
Blockface expiration reminder
Password reset

**Comment by maurizi** [comment]
@jwalgran Good catch!  I just fixed the username recovery email

**Comment by jwalgran** [comment]
+1

**Comment by dboyer** [comment]
Just got a text change from Parks. The footer text on every email should be:

Please contact us at Treescount.Help@parks.nyc.gov for technical assistance or any questions related to the TreesCount! 2015 website.

**Pull request merged**
