### PR TITLE
Add profile widgets to the dashboard

### PR DESCRIPTION
**Pull request by jwalgran**
The dashboard shows much of the same content as the user profile page. I have extracted the context generation helpers out of the users view file so they can be more easily shared with the home app.

### CODE REVIEW

**Comment by RickMohr** [comment]
For testing consider fast template tests (like `ProfileTemplateTests`) rather than slower ui tests.

**Comment by maurizi** [comment]
I'm not really a big fan of putting actual code into `__init__.py` files.

Consider moving that code into a `helpers.py` file (and possibly exposing it in `__init__.py` if you want to import it directly from `apps.users`).

**Comment by maurizi** [comment]
I agree with @RickMohr, if you're only testing markup and not behaviour, I would prefer testing the templates produced by the routed views over UI tests.

**Comment by maurizi** [comment]
Otherwise, looks good to me, +1

**Comment by jwalgran** [comment]
tests

**Comment by maurizi** [comment]
Continued +1 (modulo my comment about `__init__.py` above, which is a matter of personal taste)

**Pull request merged**
