### PR TITLE
Cleanup event title and slug validation

### LINKED ISSUE #409: Update event slug when switching from public -> private or private -> public

### LINKED ISSUE #628: Add event name validation
You shouldn't be able to create an event with a name composed of all blank spaces. 

Also, if you create an event name with symbols, it throws an error and the group detail page stops working.

We should verify that the generated slug is URL friendly. The regex validation should match the slug definition used throughout our URLs `[\w-]+`.

image

### PR DESCRIPTION
**Pull request by maurizi**
Fixes #628
Fixes #409

### CODE REVIEW

**Comment by kdeloach** [comment]
I noticed one regression related to #638. When I submit the form with an invalid Title, the Address Map lat/lng is empty.
image

**Comment by maurizi** [comment]
@kdeloach I just rebased this off of develop, I think the fix for #638 should be on this branch now

**Comment by kdeloach** [comment]
I think we also need to ensure that the event title is URL safe. I get exceptions after adding an event named `?foo=bar&baz=thing`.

**Comment by kdeloach** [comment]
+1 Title validation on adding/editing events works.

**Pull request merged**
