### PR TITLE
Fix bugs

### LINKED ISSUE #922: Add a base email template and include treescount.help@parks.nyc.gov in the footer

### LINKED ISSUE #1016: Incorrect field in registration form deletes all fields
I entered the password incorrectly in the password again field. When I clicked submit, I received a prompt to enter the same password, but the page also deleted the username and email I had entered.

### LINKED ISSUE #1017: Change subject line of activation email
Should be:

Account activation for TreesCount! 2015

### LINKED ISSUE #1019: Link to retrieve user name doesn't work
Clicking the link just returns you to the home page.

### PR DESCRIPTION
**Pull request by maurizi**
Fixes #1019
Fixes #1017
Fixes #1016
Fixes #922

### CODE REVIEW

**Comment by RickMohr** [comment]
Re #1019, should we also whitelist the URL prefixes used in `src\nyc_trees\apps\login\urls\accounts.py`?

**Comment by maurizi** [comment]
@RickMohr Those are prefixed with `/accounts/`, which is already whitelisted: https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/nyc_trees/settings/base.py#L352

**Comment by RickMohr** [comment]
Otherwise +1

**Comment by jwalgran** [comment]
+1 these fixes work

**Pull request merged**
