### PR TITLE
moved treeguard above stewardship fix #875. flip flop treeguard answers ...

### LINKED ISSUE #875: Place Tree Guards section before stewardship practices question
In the Treecorder

### LINKED ISSUE #890: Switch tree guard answer so that Not installed is on the left

### PR DESCRIPTION
**Pull request by designmatty**
...fix #890

### CODE REVIEW

**Comment by maurizi** [comment]
Can you make migrations for these label changes?  Run `./scripts/manage.sh makemigrations` and commit the file it creates.

**Comment by designmatty** [comment]
@maurizi I ran the command and it came back with "no changes detected"

**Comment by maurizi** [comment]
Ok, I guess it doesn't care when you reorder labels, only when you change them...

**Comment by maurizi** [comment]
+1

**Pull request merged**
