### PR TITLE
Fix file permission issues when running the celery worker interactively

### PR DESCRIPTION
**Pull request by maurizi**

### CODE REVIEW

**Comment by maurizi** [comment]
@RickMohr please do test

**Comment by RickMohr** [comment]
This PR has no details about the problem it was fixing, so it is difficult to test. 

Is it sufficient to start the interactive celery server and run the `dump_db` management command? 

The permissions on my `/var/www/nyc-trees/media/dump` folder are currently `drwxrwxrwx`. Probably they should be `drwxr-xr-x` to test this?

**Comment by maurizi** [comment]
@RickMohr I recreated my app VM a few days ago, and haven't changed any folder permissions.
Here is what `ls -al` shows for my `/var/www/nyc-trees/media/dump` folder:
`drwxr-xr-x 5 celery celery    4096 May  6 05:30 .`

Without this PR, every time I try and run `manage.py dump_db` while using `debugcelery.sh`, I get permission issues.

**Comment by RickMohr** [comment]
+1, tested.

**Pull request merged**
