### PR TITLE
Add link to treecorder in main navigation

### LINKED ISSUE #1252: Add Treecorder link in main navigation
Split off from #1228 

Could the Treecorder be added as an additional link in the Navigation bar, as a single point of entry to mapping functions (rather than through reservations / events)?

@jfrankl Would you see this replacing the Start Mapping button?

### PR DESCRIPTION
**Pull request by maurizi**
Redirects to the appropriate page based on the users training / individual
mapper status, # of reservations, and whether an event is in progress.

Lots of thanks to @RickMohr!

Fixes #1252

### CODE REVIEW

**Comment by jwalgran** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
It looks like the logic matches https://github.com/azavea/nyc-trees/issues/1252#issuecomment-94948310 Testing now

**Comment by jwalgran** [comment]
When a user has online training, but not field training, the redirect to individual mapper instructions 403s

screen shot 2015-04-22 at 8 21 40 am

**Comment by maurizi** [comment]
@jwalgran I fixed the issue with field training

**Comment by maurizi** [comment]
@jwalgran Nevermind, this needs some more work.

**Comment by jwalgran** [comment]
Redirect when RSVPed to an in progress training event is broken

screen shot 2015-04-22 at 8 30 37 am

click "Treecorder" in nav

screen shot 2015-04-22 at 8 30 52 am

**Comment by jwalgran** [comment]
Looks like there will be multiple fixes for this. Passing it back for now.

**Comment by maurizi** [comment]
@jwalgran I believe all issues should be fixed now

**Comment by jwalgran** [comment]
I confirmed that this link redirects to the destinations defined by https://github.com/azavea/nyc-trees/issues/1252#issuecomment-94948310

+1

**Pull request merged**
