### PR TITLE
Create management command to bust tiler cache

### PR DESCRIPTION
**Pull request by kdeloach**
Connects #1681

### CODE REVIEW

**Comment by hectcastro** [comment]
Before running the command, the tile path prefix was `1430954698`. After running the command, it changed to `1431969592`.

@jwalgran Do we also want to add this to `setupdb.sh`? It is unfortunate that it invalidates the entire cache, but that may be better than accidentally having CloudFront cache empty tiles.

**Comment by jwalgran** [comment]
We did a lot of work to make sure that a lack of cache would not over stress the tilers, so I do think we should add this as the last line of setupdb.sh, with a comment along the lines of "this must be run after all data changes"

**Comment by RickMohr** [comment]
So deploying to production will have the same effect on the CloudFront cached tiles as mapping a block. Doesn't seem like a problem.

**Comment by kdeloach** [comment]
Good suggestion. Updated `setupdb.sh` to run the `touch_blockface` management command.

**Comment by hectcastro** [comment]
:+1:

**Pull request merged**
