### PR TITLE
Add search functionality to groups list page

### LINKED ISSUE #481: Need search fields on group page
Should support searching by group and affiliation

### PR DESCRIPTION
**Pull request by steventlamb**
fixes #481 on github

### CODE REVIEW

**Comment by jwalgran** [comment]
Reviewing now

**Comment by jwalgran** [comment]
+1 Works great. You may want to ping Jeff and ask if he wants to style this box like the location search box on the map pages

screen shot 2015-02-13 at 10 53 02 am

**Comment by steventlamb** [comment]
@jfrankl do you want to style this search bar this way? It currently looks like this:

screenshot from 2015-02-13 15 15 42

If so, the only problem is that the magnifying class button doesn't really fit with the way the character-by-character search on this page. We may need to rework it.

**Comment by jfrankl** [comment]
Are you saying that this search functions differently than the address
search (one requires you to click on a button and the other doesn't)? If
so, can we make them work the same way?

On Fri, Feb 13, 2015 at 3:16 PM, Steve Lamb <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> do you want to style this search
> bar this way? It currently looks like this:
>
> [image: screenshot from 2015-02-13 15 15 42]
> <https://cloud.githubusercontent.com/assets/1699455/6194522/32807fa0-b393-11e4-9c13-7b04d00abc48.png>
>
> If so, the only problem is that the magnifying class button doesn't really
> fit with the way the character-by-character search on this page. We may
> need to rework it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/525#issuecomment-74319522>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
If we add auto searching to the geocoder (which I don't think will perform well) there still needs to be a confirmation action to make the map zoom. Geocoding will always require a click or an enter key.

**Comment by steventlamb** [comment]
Consequently, making the group search UI match would require us to do more work and receive a net loss in functionality.

**Comment by steventlamb** [comment]
merging as per @jfrankl's request to put this in as is, and open an issue for styling.

**Pull request merged**
