### PR TITLE
Prevent checking in users until an event is "starting soon".

### PR DESCRIPTION
**Pull request by maurizi**
Connects to #1568

### CODE REVIEW

**Comment by RickMohr** [comment]
The check-in links are gone, but there are still free things about the check-in page that don't make sense for the "See all RSVPs" link:
* The title of the page is "Check-in"
* The "+" button to up the RSVP limit is still active
* There is a "Start Mapping" button

Rather than trying to re-use the checkin page, why not handle "see all RSVPs" with a (scrolling) modal?

**Comment by dboyer** [comment]
What do we define as "starting soon?" How long before the event will users be able to check-in RSVPs?

**Comment by maurizi** [comment]
@dboyer The same time we use for when to show the blue alert bar - 1 hour before the event starts

**Comment by dboyer** [comment]
That's perfect. Just wanted to make sure to include that in the group admin guide.

**Comment by maurizi** [comment]
@RickMohr I've updated this with your suggestion of showing a modal instead of linking to the admin checkin page

**Comment by RickMohr** [comment]
+1, tested. Thanks for the scrollbar.

**Pull request merged**
