### PR TITLE
Fix gulp watch for JS files and add back livereload.

### LINKED ISSUE #712: Browserify builds not always completing with `gulp watch`
This was working really well at some point, except for adding new JS files after starting `watch`.

Now, the common bundle seems to get messed up quite frequently, leading to JS syntax errors.

Some googling seems to indicate that we may have just too much JS for factor-bundle and watchify to handle: https://github.com/substack/watchify/issues/112

### PR DESCRIPTION
**Pull request by maurizi**
There is a fatal interaction between factor-bundle and watchify, where
watchify will sometimes cache the wrong IDs for common modules.

Rather than trying to fix watchify or remove factor-bundle, I have opted
to remove watchify completely.

I also added back livereload functionality, which seems to have been
removed at some point.

Fixes #712

### CODE REVIEW

**Comment by kdeloach** [comment]
I get this error trying to run build-debug.

```
[15:50:55] Error: spawn ENOMEM
    at errnoException (child_process.js:1001:11)
    at ChildProcess.spawn (child_process.js:948:11)
    at exports.spawn (child_process.js:736:9)
    at Object.exports.execFile (child_process.js:618:15)
    at exports.exec (child_process.js:589:18)
    at async.eachSeries.self.emit.gutil.PluginError.stdout (/opt/app/node_modules/gulp-shell/index.js:37:19)
    at iterate (/opt/app/node_modules/gulp-shell/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/opt/app/node_modules/gulp-shell/node_modules/async/lib/async.js:165:9)
    at DestroyableTransform._transform (/opt/app/node_modules/gulp-shell/index.js:33:11)
    at DestroyableTransform.Transform._read (/opt/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
[15:50:55] 'build' errored after 19 s
[15:50:55] Error: [object Object]
    at formatError (/opt/app/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/opt/app/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/opt/app/node_modules/orchestrator/index.js:264:8)
    at /opt/app/node_modules/orchestrator/index.js:275:23
    at finish (/opt/app/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/opt/app/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/opt/app/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/opt/app/node_modules/run-sequence/index.js:55:4)
    at Gulp.emit (events.js:117:20)

npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build-debug"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.14
npm ERR! code ELIFECYCLE
npm ERR! nyc-trees@0.0.0 build-debug: `sudo -u nyc-trees ./node_modules/.bin/gulp build --debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nyc-trees@0.0.0 build-debug script 'sudo -u nyc-trees ./node_modules/.bin/gulp build --debug'.
npm ERR! This is most likely a problem with the nyc-trees package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sudo -u nyc-trees ./node_modules/.bin/gulp build --debug
npm ERR! You can get their info via:
npm ERR!     npm owner ls nyc-trees
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/npm-debug.log
Connection to 127.0.0.1 closed.
```

**Comment by maurizi** [comment]
@kdeloach Looks like an out of memory error?  Want to try upping the memory on your app VM temporarily? (the better long term solution is probably to add a swapfile on the app VM)

**Comment by kdeloach** [comment]
I halted a few VMs and reloaded my app VM to make this error go away. 

In my limited testing, watch seemed to work great. Livereload, which never worked for me before, now works.

**Comment by kdeloach** [comment]
+1

**Pull request merged**
