### PR TITLE
Restyle desktop dashboard

### LINKED ISSUE #1062: Switch to two column layout in desktop logged in homepage
The desktop version of the logged in homepage should have Events, Groups, Reservations, etc. sections arranged into a two column layout.

image

### PR DESCRIPTION
**Pull request by jfrankl**
Fixes #1062.

image

### CODE REVIEW

**Comment by jwalgran** [comment]
The spinner on the reservations printable map button appears at moble resolution but not desktop resolution

Desktop:

screen shot 2015-04-10 at 1 54 14 pm

Mobile:

screen shot 2015-04-10 at 1 54 05 pm

**Comment by jwalgran** [comment]
The desktop group list incorrectly shows +5 more groups below the group list

Desktop:

screen shot 2015-04-10 at 1 58 36 pm

Mobile:

screen shot 2015-04-10 at 1 57 50 pm

**Comment by jwalgran** [comment]
"Progress" section heading is missing and the status block over the hero image is touching the main content area.

screen shot 2015-04-10 at 2 14 04 pm

**Comment by jfrankl** [comment]
Thanks @jwalgran. These issues should now be fixed. Please take another look when you have a chance.

image

image

**Comment by RickMohr** [comment]
Did you intentionally remove the "TREES MAPPED" label underneath the odometer? Seems like it would be useful to have it there.

**Comment by jwalgran** [comment]
+1 looks great.

I agree that, without a label, it's not 100% obvious what is being counted by the odometer.

**Comment by jfrankl** [comment]
The "Trees Mapped" label returns!

image

**Pull request merged**
