### PR TITLE
cleaned up training page materials - fixes #1188

### LINKED ISSUE #1188: Design needs for training materials
The training materials are in place on staging. Some design assistance is needed for:

1. Bulleted list isn't showing up as bulleted - training/progress/the_mapping_method/
2. Spacing between images and text. Some of pages would be more readable with an extra line between the image and the next paragraph of text. 
3. Size of images on tree trunk size page. They're a little large.
4. Green Ash and Swamp Oak images on tree species page are too large.
5. Material in “Perceptions of Tree Health” is supposed to be in a box as marked on the flat pages. Not sure if this will work with the layout available.

### PR DESCRIPTION
**Pull request by designmatty**

### CODE REVIEW

**Comment by jwalgran** [comment]
Reviewing now

**Comment by jwalgran** [comment]
Confirmed bulleted lists in "The Mapping Method"

screen shot 2015-04-21 at 3 00 44 pm

**Comment by jwalgran** [comment]
Confirmed the ``max-height`` keeps trunk size images in check

screen shot 2015-04-21 at 3 16 11 pm

**Comment by jwalgran** [comment]
Confirmed species image size

screen shot 2015-04-21 at 3 17 37 pm

**Comment by jwalgran** [comment]
I confirmed that closing ``p`` tags has added whitespace between text and images.

I am not sure about how to verify

    Material in “Perceptions of Tree Health” is supposed to be in a box as marked on the flat
    pages. Not sure if this will work with the layout available.

+1 if that item from #1188 is resolved

**Comment by dboyer** [comment]
@jwalgran I discussed the content boxes with @designmatty and he added some background shading where possible to pull together certain images and text. I consider that problem solved.

**Comment by designmatty** [comment]
@jwalgran certain portions of content will be surrounded by `<figure>` which will box in the content.

This will have required you to rebuild your training pages (admittedly, something I should have mentioned).

**Comment by steventlamb** [comment]
+1

**Comment by jwalgran** [comment]
+1

**Pull request merged**
