### PR TITLE
Reservations: don't generate map tiles at low zooms

### PR DESCRIPTION
**Pull request by RickMohr**
Connects #1593

### CODE REVIEW

**Comment by jwalgran** [comment]
+1 this works perfectly. I played with the styling a little to try and direct peoples attention to go to the action bar. What do you think about bold and blue for the low zoom instructions?

screen shot 2015-05-11 at 1 01 38 pm

**Comment by RickMohr** [comment]
Good idea to make that text more noticeable. Blue might not be best though since we use it for links a lot of places. @designmatty, what do you think?

**Comment by designmatty** [comment]
Two thoughts:

1: I think $brand-primary (green) would work better since like @RickMohr said, blue is reserved for links.
2: What if you only made changes to the "Zoom In" text? Bolded it and made it green instead of blue and left the rest of the text as is. Just a thought.

**Comment by RickMohr** [comment]
@designmatty, how would I best apply that? From the source it looks like `label-primary` should work, but `<span class="label-primary">Zoom in</span>` doesn't change the color.

**Comment by RickMohr** [comment]
Somewhat more noticeable:
capture

**Comment by jwalgran** [comment]
I like just highlighting the action a lot.

**Pull request merged**
