### PR TITLE
Allow anonymous users to access the achievements page.

### LINKED ISSUE #1435: Achievements page on production is requiring login to view

### PR DESCRIPTION
**Pull request by maurizi**
Fixes #1435 

I coordinated with @jfrankl on the header text / design.

### CODE REVIEW

**Comment by maurizi** [comment]
achievements

**Comment by jfrankl** [comment]
Deb, the other option we discussed is removing the header entirely. I think
that could look good too. I don't think we should use the "Earned" sort of
language—I think that's confusing before you have an account.

On Fri, Apr 24, 2015 at 11:24 AM, Michael Maurizi <notifications@github.com>
wrote:

> [image: achievements]
> <https://cloud.githubusercontent.com/assets/4432106/7322182/8170f186-ea74-11e4-979a-7eec30f3daf3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/1438#issuecomment-95965617>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by RickMohr** [comment]
+1, tested.

**Comment by dboyer** [comment]
Chiming in late on this but I agree with @jfrankl that we should not use the Earned heading. All Achievements is fine for anonymous users.

**Pull request merged**
