### PR TITLE
Only count completed surveys when determining progress and map styling

### PR DESCRIPTION
**Pull request by maurizi**
Connects to #1582

### CODE REVIEW

**Comment by maurizi** [comment]
Some unit tests are failing, I'll reassign this once it is ready

**Comment by maurizi** [comment]
Unit tests fixed

**Comment by kdeloach** [comment]
I can't reproduce the original issue. If I select "I cannot map this block because..." and enter a quit reason, I still have the block reserved.

**Comment by maurizi** [comment]
@kdeloach As we discussed, this does not fix issues around whether the blockface is still consider reserved, only what color it is styled as.  Reservation issues will be handled as part of a different PR.

**Comment by kdeloach** [comment]
I was confused by another issue #1573. After testing again, it appears to be working.

**Comment by kdeloach** [comment]
+1

**Pull request merged**
