### PR TITLE
Show "Start Mapping" button for events in-progress

### LINKED ISSUE #1068: If you are checked in to an in-progress event, the event page does not have a "Start Mapping" button
Page before the person is checked in

screen shot 2015-04-06 at 8 24 07 am

Page after the person is checked in

screen shot 2015-04-06 at 8 24 20 am

### PR DESCRIPTION
**Pull request by kdeloach**
Fixes #1068

### CODE REVIEW

**Comment by kdeloach** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
Fixing tests now.

**Comment by kdeloach** [comment]
And by fixing tests I mean deleting tests.

**Comment by RickMohr** [comment]
With this change the "!" alert in the header remains even after you are checked in. It is supposed to disappear once you check in. Also, I think we should not be showing the "Start Mapping" button until you are checked in. I think we need some additional logic; `my_events_now` won't suffice for both.

**Comment by kdeloach** [comment]
Back to the drawing board!

**Comment by kdeloach** [comment]
I think I accidentally force pushed develop HEAD to this branch during a rebase gone wrong, which caused GitHub to automatically close my PR.

**Comment by kdeloach** [comment]
How this works now:
  1. "Start Mapping" button is displayed (on sidebar and event detail page) when you have an upcoming/in-progress event that you have RSVPd for. The header notification also displays.
  2. Once checked-in to your event, the "Start Mapping" buttons remain, but the header notification goes away.

**Comment by RickMohr** [comment]
+1

**Pull request merged**
