### PR TITLE
Feature/mw/group logo styling

### LINKED ISSUE #264: Clean up group logos
Currently, group logos are bound by a circle. This needs to be cleaned up by vertically centering the logo within the circle.

Also, it would be good to test this with a wide variety of logo dimensions. This element might change in the final visual designs, so I will wait until that has been finalized before I spend more time cleaning it up.

### PR DESCRIPTION
**Pull request by designmatty**
fixes #264

### CODE REVIEW

**Comment by jfrankl** [comment]
@designmatty I'm still getting white space when the image isn't a square. Is that what you see? Not 100% sure it's possible, but ideally we'd be able to handle this in the css to display an image with no surrounding white space.

Horizontally oriented logo:

image

Vertically oriented logo:

image

**Comment by designmatty** [comment]
@jfrankl I still have not found a solid way to accomplish this using the ``. Fixing horizontal white space for horizontally oriented images creates vertical white space and vise versa.

I did however found a solution that essentially changes from using an `` to a `<div>` with the image standing in as a `background-image`.

Take a look at this as an example http://codepen.io/jvanderkroon/pen/qniAx/

**Comment by jfrankl** [comment]
Using background-size: cover sounds good to me. Seems like it should
work—could you just be sure to test it on the three scenarios we talked
about (square image, vertical image, horizontal image)?

On Thu, Apr 16, 2015 at 4:45 PM, Matt Williams <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> I still have not found a solid way
> to accomplish this using the . Fixing horizontal white space for
> horizontally oriented images creates vertical white space and vise versa.
>
> I did however found a solution that essentially changes from using an
>  to a <div> with the image standing in as a background-image.
>
> Take a look at this as an example
> http://codepen.io/jvanderkroon/pen/qniAx/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/1163#issuecomment-93835813>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by designmatty** [comment]
Yeah I'll test this out today.

**Comment by jfrankl** [comment]
+1. background-imazing!

**Pull request merged**
