### PR TITLE
Add blockface reservation page with map

### PR DESCRIPTION
**Pull request by jwalgran**

### CODE REVIEW

**Comment by maurizi** [comment]
Looks good to me

**Comment by steventlamb** [comment]
I've got an alignment issue when checking this branch out:
screenshot from 2015-01-19 11 26 42

**Comment by steventlamb** [comment]
I hadn't run `npm build debug`, but the issue persists after I do:
screenshot from 2015-01-19 11 28 43

**Comment by jwalgran** [comment]
@jfrankl could I get an assist? The new ``/blockface`` page in my ``feature/jcw/reservation-map`` branch has a title alignment problem. The ``base_two_frames.html`` template did not seem for a full screen map page.

**Comment by steventlamb** [comment]
+1 pulled down and tested.

**Comment by jwalgran** [comment]
@steventlamb I made a new ``apps.core.views`` module to contain the map legend context view in 19a84dc94894c992b083958ae84f84b84b416881. Is this what you were thinking?

**Comment by steventlamb** [comment]
Yes, this last commit is what I was thinking.

**Comment by jwalgran** [comment]
@azavea-bot rebuild

**Comment by jfrankl** [comment]
Justin, could you tell me more about the title alignment problem?

On Mon, Jan 19, 2015 at 11:33 AM, Justin Walgran <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> could I get an assist? The new
> /blockface page in my feature/jcw/reservation-map branch has a title
> alignment problem. The base_two_frames.html template did not seem for a
> full screen map page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/pull/305#issuecomment-70522082>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
@jfrankl Here is what http://localhost:8000/blockface/ looks like

screen shot 2015-01-20 at 11 27 43 am

**Comment by jwalgran** [comment]
@jfrankl here is what http://localhost:8000/blockface/ looks like 

offscreen

I could not get the title to show up with the proper left margin

**Comment by jwalgran** [comment]
@jfrankl that worked. Thanks. I'll get these changes into another pull.

**Pull request merged**
