### PR TITLE
Make the territory map selected blocks transparent.

### PR DESCRIPTION
**Pull request by maurizi**
This should allow determining what color the underlying block edge is,
and if it is mapped or unmapped, while still making it easy to determine
which block edges are selected or unselected.

Connects to #1801

### CODE REVIEW

**Comment by maurizi** [comment]
territory

**Comment by RickMohr** [comment]
While this addresses the specific complaint it seems likely to add confusion, since there are now many new colors to understand and they aren't shown in the legend. What does orange mean? What does it mean if I click on a blue block and it turns green? Why is yellow in the legend?

As an alternative, how about using a dashed yellow (opaque) line for the selected blocks?

**Comment by jwalgran** [comment]
I agree that transparency didn't work as well as I though due to color mixing. Skinny fully opaque yellow lines or using  [``dashArray``](http://leafletjs.com/reference.html#path-dasharray) may be a . If not, a big button to toggle the visibility of the yellow selection layer may be enough.

**Comment by dboyer** [comment]
Yeah, let's avoid additional colors. There are enough already. I agree with Justin's suggestions.

**Comment by maurizi** [comment]
Closed in favor of https://github.com/azavea/nyc-trees/pull/1804

**Pull request closed without merging**
