### PR TITLE
Restore privacy popup

### LINKED ISSUE #522: Restore privacy popup
See #436.

The privacy popup was mistakenly removed in https://github.com/azavea/nyc-trees/commit/fcd54630d7156ccb8934b125f8228a003da83b95#diff-a021a948cbde19d1349cfea855f17517L82. It should be restored, and show only when clicking the privacy button on the profile page.

screen shot 2015-02-13 at 9 12 19 am

### PR DESCRIPTION
**Pull request by steventlamb**
fixes #522 on github

### CODE REVIEW

**Comment by jwalgran** [comment]
There is a unit test failure because a word now appears multiple times

**Comment by jwalgran** [comment]
``/opt/app/apps/home/tests.py:34:9: E731 do not assign a lambda expression, use a def``

**Comment by steventlamb** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
The popup is back. +1

**Comment by steventlamb** [comment]
merged because the CI build passed, as did mine

**Pull request merged**
