### PR TITLE
Zoom to user location on survey page

### PR DESCRIPTION
**Pull request by kdeloach**
This adds a new option to the map to geolocate the user location on
page load.

Connects #1253

### CODE REVIEW

**Comment by kdeloach** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
Rebased onto develop.

**Comment by kdeloach** [comment]
Waiting to find out if the last commit should be included at all in this PR.

**Comment by kdeloach** [comment]
Rebased onto develop and added help popup for the geolocate button on the survey page.

On desktop:

image

On mobile / smaller window size:

image

**Comment by RickMohr** [comment]
How about "Move the map to your location" instead of "Geolocate the map to your location"?

**Comment by RickMohr** [comment]
+1, tested

**Comment by RickMohr** [comment]
Nice-looking arrow!

**Comment by kdeloach** [comment]
Rebased onto develop and changed the popup text.

**Pull request merged**
