### PR TITLE
Case-insensitive logins

### LINKED ISSUE #945: Make user IDs not case sensitive

### PR DESCRIPTION
**Pull request by RickMohr**
Fixes #945

### CODE REVIEW

**Comment by steventlamb** [comment]
This looks like the right way to do this, but I can't find a canoncal reference to this technique. This is all I found, which is only tangentially related:
https://docs.djangoproject.com/en/1.7/topics/serialization/

For my education, can you provide some background into the decision process?

**Comment by steventlamb** [comment]
+1 tested, works

**Comment by jwalgran** [comment]
Merging for Rick while he is out of the office

**Comment by RickMohr** [comment]
@steventlamb, I got the idea to override `get_by_natural_key` from a comment in https://djangosnippets.org/snippets/1368/ and to change
`AuthenticationForm.error_messages['invalid_login']` from reading the `django-registration` code.

**Pull request merged**
