### PR TITLE
Remove inline teammate autocomplete in favor of AJAX backed autocomplete

### PR DESCRIPTION
**Pull request by maurizi**
The select tag based autocomplete was proving to be not performant enough
with a significant number of users (over 3000).

Moving to an AJAX-based autocomplete should alleviate the performance
issues we have encountered with it.

Connects to #1726

### CODE REVIEW

**Comment by kdeloach** [comment]
:clap:

**Comment by jwalgran** [comment]
There is a style regression that can be fixed with ``<input id="teammate-select" />`` → ``<input class="teammate" id="teammate-select" />``

**Comment by jwalgran** [comment]
There is some crummy grammar in the select2 help text

screen shot 2015-06-26 at 8 22 55 am

Looks like this is the offending line

https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/js/shim/select2.js#L3505
```javascript
formatInputTooShort: function (input, min) { var n = min - input.length; return "Please enter " + n + " or more character" + (n == 1 ? "" : "s"); },
```

We may want to patch this line directly in ``shim/select2.js`` rather than worry about an upgrading the library to get such a small fix. 

stego

**Comment by maurizi** [comment]
@jwalgran I pushed a change to fix the styling regression.  As for the select2 text, I'm not really sure what you're suggesting I change it to.  The grammar seems Ok, if not perfect.  Do you have a suggestion for what to change it to?

**Comment by jwalgran** [comment]
+1

On my iPhone 4s I verified that I can still search for teammates with either username or full names (when the mapper has made their full name public)

I exercised this with Chrome mobile mode throttling the connection to "Regular 2G 250kbps". Typing the letter "a" matches just over 1600 results, and the response returned in about 800ms, which is good.

screen shot 2015-06-26 at 9 41 46 am

On "Good 3g" this drops to < 200ms

screen shot 2015-06-26 at 9 51 39 am

I dumped the query generated by the endpoint and it runs in about ~7ms with current production data, which is also good, and suggests that we will be able to handle a much larger user count in the future if we need to.

```
EXPLAIN ANALYZE SELECT "core_user"."id", "core_user"."password", "core_user"."last_login", "core_user"."is_superuser", "core_user"."username", "core_user"."first_name", "core_user"."last_name", "core_user"."email", "core_user"."is_staff", "core_user"."is_active", "core_user"."date_joined", "core_user"."created_at", "core_user"."updated_at", "core_user"."individual_mapper", "core_user"."requested_individual_mapping_at", "core_user"."profile_is_public", "core_user"."real_name_is_public", "core_user"."group_follows_are_public", "core_user"."contributions_are_public", "core_user"."achievements_are_public", "core_user"."is_flagged", "core_user"."is_banned", "core_user"."is_ambassador", "core_user"."is_minor", "core_user"."zip_code", "core_user"."referrer_parks", "core_user"."referrer_group_id", "core_user"."referrer_ad", "core_user"."referrer_social_media", "core_user"."referrer_friend", "core_user"."referrer_311", "core_user"."referrer_other", "core_user"."field_training_complete", "core_user"."training_finished_getting_started", "core_user"."training_finished_the_mapping_method", "core_user"."training_finished_tree_data", "core_user"."training_finished_tree_surroundings", "core_user"."training_finished_wrapping_up", "core_user"."training_finished_intro_quiz", "core_user"."training_finished_groups_to_follow", "core_user"."opt_in_stewardship_info", "core_user"."progress_page_help_shown", "core_user"."survey_geolocate_help_shown", "core_user"."reservations_page_help_shown", "core_user"."reservation_ids_in_map_pdf", "core_user"."reservations_map_pdf_filename" FROM "core_user" WHERE (NOT ("core_user"."id" = 611) AND "core_user"."is_active" = True AND (UPPER("core_user"."username"::text) LIKE UPPER('%a%') OR ("core_user"."real_name_is_public" = True AND (UPPER("core_user"."first_name"::text) LIKE UPPER('%a%') OR UPPER("core_user"."last_name"::text) LIKE UPPER('%a%'))))) ORDER BY "core_user"."username" ASC;

 Sort  (cost=321.12..327.45 rows=2531 width=206) (actual time=7.162..7.253 rows=1638 loops=1)
   Sort Key: username
   Sort Method: quicksort  Memory: 519kB
   ->  Seq Scan on core_user  (cost=0.00..178.05 rows=2531 width=206) (actual time=0.013..2.951 rows=1638 loops=1)
         Filter: (is_active AND (id <> 611) AND ((upper((username)::text) ~~ '%A%'::text) OR (real_name_is_public AND ((upper((first_name)::text) ~~ '%A%'::text) OR (upper((last_name)::text) ~~ '%A%'::text)))))
         Rows Removed by Filter: 1382
 Total runtime: 7.374 ms
```

**Comment by jwalgran** [comment]
On the topic of the help text grammar,  when a sentence includes "or more" I think it suggests using the plural noun. The latest version of select2 implements this.

https://github.com/select2/select2/blob/bd6148e39f753ed2880f674a90b42ffe446b893a/src/js/select2/i18n/en.js#L21

```javascript
var message = 'Please enter ' + remainingChars + ' or more characters';
```

Googling reveals that there is some contention between grammar experts on the topic. I am cool with leaving it alone.

**Pull request merged**
