### PR TITLE
Topic/training quiz prerequisites

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by jwalgran** [comment]
Looks good. Testing now.

**Comment by jwalgran** [comment]
Do we not yet have correct answers for this question?

screen shot 2015-04-10 at 1 24 45 pm

screen shot 2015-04-10 at 1 24 55 pm

**Comment by steventlamb** [comment]
That question is awaiting a photo, but it should work otherwise. Does (4) not work for you?

**Comment by jwalgran** [comment]
np. It does work. answers look funny without the photo.

**Comment by jwalgran** [comment]
+1

I used the script to load the new flatpages and was able to walk through the whole training process

Deep links to anchor IDs works in Safari

screen shot 2015-04-10 at 1 43 55 pm

**Pull request merged**
