### PR TITLE
PREVIEW: send paper worksheet

### PR DESCRIPTION
**Pull request by steventlamb**
@jwalgran this looks like it'll work, how do you want to handle storing and retrieving the PDF?

### CODE REVIEW

**Comment by jwalgran** [comment]
We have the training material PDF in our static content folder, so that is where I would expect this other, static PDF to be saved. We could pull it from the filesystem using ``settings.STATIC_ROOT + 'what/ever/subpath/TreesCount2015_worksheet.pdf``

**Comment by jwalgran** [comment]
I like where this is headed.

**Comment by steventlamb** [comment]
@jwalgran soft-coded the path, ran tests, poked the modified the other changed email tasks. Ready for official review.

**Comment by jwalgran** [comment]
Testing now.

**Comment by jwalgran** [comment]
+1 confirmed that 2 PDFs were attached when I selected paper mapping. Existing RSVP PDF emailing still works as before.

**Pull request merged**
