### PR TITLE
Fix exception when anonymous user visits training instructions

### PR DESCRIPTION
**Pull request by kdeloach**
Connects #1177

### CODE REVIEW

**Comment by kdeloach** [comment]
@azavea-bot rebuild

**Comment by RickMohr** [comment]
+1, tested.

**Comment by kdeloach** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
PR builder test failures seem completely unrelated to this (geocoding unit tests). I think this is safe to merge.

**Pull request merged**
