### PR TITLE
Topic/embedded training questions

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by steventlamb** [comment]
This gets us really close to having embedded exercises. Right now question feedback is displayed in an alert, for demo purposes.

**Comment by steventlamb** [comment]
In addition to finishing the feature according to the spec, when decided, documentation is also necessary.

**Comment by jwalgran** [comment]
looking at this now

**Comment by jwalgran** [comment]
+1 works well

**Comment by hectcastro** [comment]
Can we include something like this at the bottom of `setupdb.sh` as part of this PR?

```bash
# Create training flatpages
envdir /etc/nyc-trees.d/env/ /opt/app/manage.py make_training_flatpages || true
```

**Comment by steventlamb** [comment]
@hectcastro that would work, or we can just change this mgmt command to return zero when records exist, instead of failing.

**Comment by steventlamb** [comment]
Pushed 3 commits to finish this feature according to @jfrankl's sketches.

**Comment by kdeloach** [comment]
+1

**Pull request merged**
