### PR TITLE
Text changes per Parks.

### PR DESCRIPTION
**Pull request by RickMohr**
Connects #1782

### CODE REVIEW

**Comment by RickMohr** [comment]
* "Achievements" is changed everywhere to "Rewards"
* Extra reward text only shows up for rewards you have earned

**Comment by RickMohr** [comment]
Investigating the failing test now.

**Comment by RickMohr** [comment]
Test fixed. (Failure was caused by a bad character pasted in from Parks text)

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
+1

**Pull request merged**
