### PR TITLE
New reserations workflow

### LINKED ISSUE #965: Implement new reservations page
From Jeff's wireframes - 2015_03_26_nyc_wireframes_v4.pdf p14-30

### PR DESCRIPTION
**Pull request by maurizi**
This PR reworks the reservations pages, combining them into one.

The new workflow shows both current reservations and those in your shopping cart, and allows for cancelling reservations and creating new ones as part of the same process.

Fixes #965

### CODE REVIEW

**Comment by maurizi** [comment]
@jfrankl Can you pull this down and play around with it to see if there is anything in the wireframes this doesn't capture?

**Comment by maurizi** [comment]
This is missing a couple of minor things that I'm working to fix:
 - [ ] Add some comments for URLs in JS code
 - [ ] Changes to the legend swatches

**Comment by jfrankl** [comment]
Nice Mike.

One change: can the selected block always be yellow?

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by RickMohr** [comment]
The page title is "New Reservation". The spec shows "Reservations".

**Comment by RickMohr** [comment]
When clicking on a blockface you have reserved you see this:

image

I suggest instead:

Reserved by you (until Apr 20)

**Comment by RickMohr** [comment]
If I select a block and don't want to do the presented action (e.g. Add to Cart) but do want to click "Finish Reservations" there's nothing visible showing me how to do that. I have to figure out that clicking the selected block again will do it. The spec has a big left arrow for that purpose.

**Comment by RickMohr** [comment]
Two problems:

1) If I have one block already reserved and I click "Remove" it correctly turns black, but the "Finish Reservation" button is disabled so I can't actually remove it. 

2) If I try to select it again I get "Unavailable Block Edge. The block edge you selected has already been reserved."

**Comment by RickMohr** [comment]
If I hit the back button on the checkout page my cart is emptied. That seems bad. I can hit the forward button and successfully check out the blocks, so clearly the cart contents are stored.

We might want to reconsider persisting the cart state.

**Comment by RickMohr** [comment]
On the checkout page these sentences need periods:

You have requested 1 block edge reservation

You are cancelling 3 block edge reservations

**Pull request merged**
