### PR TITLE
Event start mapping page

### PR DESCRIPTION
**Pull request by kdeloach**
This adds a new page so the user can select a blockface to survey from the list of available group blockfaces.

Click the "Start Mapping" button on the user checkin page to access this page.

### CODE REVIEW

**Comment by kdeloach** [comment]
I may rename or move some files around but I think the majority of this feature is complete.

**Comment by hectcastro** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
More work is needed for this PR. Link up all "Start Mapping" references and create endpoints for event mappers and individual mappers.

**Comment by kdeloach** [comment]
This should include all the changes we talked about. Try to access the survey page from the Reservations page (as an individual mapper) or from an event. Click any "Start Mapping" URL to access the survey page. You can also append `#12345` (blockface ID) to zoom into that blockface on the survey page.

I still have to refine the survey views but it's mostly there and ready for testing.

**Comment by RickMohr** [comment]
We will want to remove the displayed blockface ID and "Survey" button, but it's fine with me to do it in the PR that adds selection of endpoint and side of street.

**Comment by kdeloach** [comment]
@azavea-bot rebuild

**Comment by RickMohr** [comment]
+1

**Pull request merged**
