### PR TITLE
Allow mapping at events all day

### PR DESCRIPTION
**Pull request by maurizi**
- Refactors treecorder link to show a modal when there is ambiguity about how to survey
- Allows mapping events until midnight the day of the event, if the user was checked in to that event

Connects to #150

### CODE REVIEW

**Comment by maurizi** [comment]
@dboyer Let me know what you think of the text here:
modal1

**Comment by dboyer** [comment]
Let's change "how do you want to map" to "where do you want to map." When someone reserves block edges, they are asked about how they want to map in terms of paper vs. app so I'd rather use where here, not how.

Also, take out the comma after event. Otherwise, I think it's good.

**Comment by kdeloach** [comment]
Should we also update the dashboard to show a notification for each event in progress? Right now it only shows the first one.

image

**Comment by kdeloach** [comment]
I have to click links in the modal window twice for it to work. The first time I click the nav deactivates.

image

image

**Comment by dboyer** [comment]
Ideally, we would show the notification for each event in progress, but do we have space for that?

**Comment by maurizi** [comment]
@dboyer I don't think we have the space for it, especially on mobile.  @jfrankl or @designmatty could weigh in, but I remember discussing showing multiple event alerts there before and ditching the idea.

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by RickMohr** [comment]
I think it should say "Map my reserved block edges" instead of "Map your reserved block edges"

**Comment by maurizi** [comment]
@kdeloach The modal nav menu issue we discussed is fixed

**Comment by RickMohr** [comment]
Otherwise +1. Tested a lot of cases and they all worked.

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
+1

**Comment by dboyer** [comment]
I'm fine with only showing one notification for an event starting soon.

**Pull request merged**
