### PR TITLE
Add polling to user event checkin page

### PR DESCRIPTION
**Pull request by kdeloach**
This will poll an endpoint every few seconds to determine if the user has
been checked-in by an admin yet. When the user is checked-in they will
be redirected to the event detail page.

### CODE REVIEW

**Comment by kdeloach** [comment]
@RickMohr Updated. Though I'm still not sure where "Start Mapping" is supposed to go.

**Comment by RickMohr** [comment]
+1

**Comment by maurizi** [comment]
+1

**Comment by kdeloach** [comment]
Thanks @RickMohr, I know you have a lot of other stuff going on this week.

**Pull request merged**
