### PR TITLE
Remove "Groups" view from progress map

### PR DESCRIPTION
**Pull request by RickMohr**
Connects #1838

### CODE REVIEW

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by maurizi** [comment]
I'm getting the following error when trying to provision from scratch:
```
TASK [azavea.java : Install OpenJDK JRE (headless)] ****************************
fatal: [services]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'openjdk-7-jre-headless=7u75-*'' failed: E: Version '7u75-*' for 'openjdk-7-jre-headless' was not found\n", "stderr": "E: Version '7u75-*' for 'openjdk-7-jre-headless' was not found\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}
```

**Comment by RickMohr** [comment]
@maurizi, try it now

**Comment by maurizi** [comment]
This makes the progress map look a little odd when logged out, since there is a dropdown to choose your mode, but it has only one option of "All Users".  I think we need to change it from a dropdown to a simple label if the user is logged out.

**Comment by maurizi** [comment]
:+1: after squashing commits

**Pull request merged**
