### PR TITLE
Topic/survey detail controls

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by jwalgran** [comment]
I think "No -Start Over" should include the blockface ID in the URL hash so the same block is selected on reload.

**Comment by jwalgran** [comment]
If they say "No - Submit for review" we need to hit the ``flag_survey`` endpoint before asking what they would like to do next.

**Comment by steventlamb** [comment]
@jwalgran how's that look?

**Comment by jwalgran** [comment]
+1 all three options work perfectly

**Pull request merged**
