### PR TITLE
Add new achievements

### PR DESCRIPTION
**Pull request by maurizi**
New achievements are temporarily using the image for 'Mayoral Mapper'
until the final images are decided upon.

To enable showing what achievements a user already has, a data migration
will update achievements for all users to record their what their inactive
achievements are, since they are no longer active for 2016 and cannot be
unlocked with new surveys.

Connects to #1836

### CODE REVIEW

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
Using a prod snapshot counted the achievements before running the migration, and then after. As expected, some users received additional achievement rows.

**Comment by jwalgran** [comment]
👍

**Pull request merged**
